# Lab: Dashboarding with in-class Data Examples

This Lab will give you some practice building dashboards to create interactive plots.

This first part of the lab will go over some of the concepts we went over in class in which we created a grid heatmap using randomly generated data (with a few extra twists!).

This is a model for how to build a dashboard with *categorical* rows and columns.

**NOTE: It is *highly* recommended that you hit "Save & Grade" after you answer each prompt in order to catch any errors in order.**

## Step 1: Create the 3D, random dataset

Use numpy to set the seed and create this dataset with:

```python
import numpy as np

np.random.seed(42) 
data3d = np.random.random((10,10,20))
```

**Double check the names of these variables.**

Note that we are setting the "seed" of the randomly generated data so that you will get the same "random" data as the autograder.

In [1]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
import numpy as np

np.random.seed(42)
data3d = np.random.random((10, 10, 20))
print(data3d)

[[[0.37454012 0.95071431 0.73199394 ... 0.52475643 0.43194502 0.29122914]
  [0.61185289 0.13949386 0.29214465 ... 0.09767211 0.68423303 0.44015249]
  [0.12203823 0.49517691 0.03438852 ... 0.19598286 0.04522729 0.32533033]
  ...
  [0.96244729 0.2517823  0.49724851 ... 0.76161962 0.23763754 0.72821635]
  [0.36778313 0.63230583 0.63352971 ... 0.38673535 0.93672999 0.13752094]
  [0.34106635 0.11347352 0.92469362 ... 0.89711026 0.88708642 0.77987555]]

 [[0.64203165 0.08413996 0.16162871 ... 0.74649141 0.6496329  0.84922341]
  [0.65761289 0.5683086  0.09367477 ... 0.02431597 0.6454723  0.17711068]
  [0.94045858 0.95392858 0.91486439 ... 0.6960298  0.57006117 0.09717649]
  ...
  [0.49161588 0.47347177 0.17320187 ... 0.58577558 0.94023024 0.57547418]
  [0.38816993 0.64328822 0.45825289 ... 0.02327194 0.81446848 0.28185477]
  [0.11816483 0.69673717 0.62894285 ... 0.42899403 0.75087107 0.75454287]]

 [[0.10312387 0.90255291 0.50525237 ... 0.32866455 0.67251846 0.75237453]
  [0.79157904 0.789618

## Step 2: Create color, x, y scales

Create a color scale with the "Blues" color scheme.  **Call this variable `colsc`.**

Create an x-scale and **call this variable `xsc`**.  Hint: what [type of scale](https://bqplot.github.io/bqplot/api/scales/) should you use for this variable?

Create an y-scale and **call this variable `ysc`**.  Hint: same question of scale type for the x-scale.


In [2]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
import bqplot
from bqplot import pyplot as plt

colsc = bqplot.ColorScale(scheme='Blues')
xsc = bqplot.OrdinalScale()
ysc = bqplot.OrdinalScale()

print(colsc)
print(xsc)
print(ysc)

ColorScale(scheme='Blues')
OrdinalScale()
OrdinalScale()


## Step 3: Create color, x, y axis

Create a color axis **called this variable `colax`.**  Place this color axis on the top of the plot, horizontally.

Create an x-axis and **call this variable `xax`**.  Label this axis with the text "X-Variable".

Create an y-axis and **call this variable `yax`**.  Label this axis with the text "Y-Variable".

Place the x/y axis in the "usual" places for these types of axis.

**NOTE:** for testing purposes, make sure all of the placements/choices are explicit (i.e., don't rely on the defaults for any of these objects).

In [3]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
colax = bqplot.ColorAxis(scale=colsc, orientation='horizontal', side='top')
xax = bqplot.Axis(scale=xsc, orientation='horizontal', label='X-Variable', side='bottom')
yax = bqplot.Axis(scale=ysc, orientation='vertical', label='Y-Variable', side='left')

print(colax)
print(xax)
print(yax)

ColorAxis(scale=ColorScale(scheme='Blues'), side='top')
Axis(label='X-Variable', scale=OrdinalScale(), side='bottom')
Axis(label='Y-Variable', orientation='vertical', scale=OrdinalScale(), side='left')


## Step 4: Create heat map

Create a "GridHeatMap" and **call this variable `heatmap`** using your previously created `colsc`, `xsc` and `ysc` scales.

The `color` of this grid heatmap should be the *mean* of `data3d` on its 3rd axis (i.e., along the "longest" axis).

Add in an interaction in which you `select` when you `click`.  When a cell is selected, fill the cell with the color red.

In [4]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
heatmap = bqplot.GridHeatMap(color=np.mean(data3d, axis=2),
                                scales={'color': colsc, 'row': ysc, 'column': xsc},
                                interactions={'click': 'select'},
                                selected_style={'fill': 'red'})

print(heatmap)

GridHeatMap(color=array([[0.45770229, 0.45482896, 0.48997106, 0.46105824, 0.48734317,
        0.51175678, 0.49517039, 0.45929713, 0.43190783, 0.59102649],
       [0.44849294, 0.4749017 , 0.61039877, 0.6646432 , 0.38957005,
        0.46973143, 0.45961324, 0.46447998, 0.43728366, 0.62463639],
       [0.54350696, 0.43311305, 0.48503318, 0.56656882, 0.55200711,
        0.59203293, 0.62292703, 0.5409094 , 0.50213883, 0.36849053],
       [0.41471592, 0.41818533, 0.44153972, 0.43655441, 0.44693686,
        0.51728155, 0.50360367, 0.56964968, 0.48017894, 0.55906542],
       [0.56327921, 0.46405485, 0.40094097, 0.44008667, 0.41026101,
        0.45690497, 0.48774946, 0.48312332, 0.4302379 , 0.49793629],
       [0.57996281, 0.5182848 , 0.58460319, 0.471571  , 0.5122255 ,
        0.51749191, 0.52746438, 0.64852668, 0.52489542, 0.55149071],
       [0.46143442, 0.52405098, 0.51620815, 0.425521  , 0.38434132,
        0.53234389, 0.50231104, 0.56949764, 0.54068199, 0.46302624],
       [0.45047681, 0.4

## Step 5: Create a label widget

Call this widget **heatmap_label**.

In [5]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
import ipywidgets as widgets

heatmap_label = widgets.Label()

## Step 6: Create an interaction/"on selection" function

Create a function **called `on_selection`** which is tied to the heatmap with an `.observe` call on the `heatmap`'s `selected` key.

The function should only allow for *one* selection at a time (i.e., no multiple cell selection).

The function should change the `heatmap_label` value to the *sum* of the data along the third axis of `data3d`.

In [6]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)


## Step 7: Create the heatmap figure

Combine the heatmap and appropriate axes into a `bqplot` figure object.  **Call this variable `fig`.**

In [7]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
fig = bqplot.Figure(marks=[heatmap], axes=[colax, xax, yax])

print(fig)

Figure(axes=[ColorAxis(scale=ColorScale(scheme='Blues'), side='top'), Axis(label='X-Variable', scale=OrdinalScale(), side='bottom'), Axis(label='Y-Variable', orientation='vertical', scale=OrdinalScale(), side='left')], fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.45770229, 0.45482896, 0.48997106, 0.46105824, 0.48734317,
        0.51175678, 0.49517039, 0.45929713, 0.43190783, 0.59102649],
       [0.44849294, 0.4749017 , 0.61039877, 0.6646432 , 0.38957005,
        0.46973143, 0.45961324, 0.46447998, 0.43728366, 0.62463639],
       [0.54350696, 0.43311305, 0.48503318, 0.56656882, 0.55200711,
        0.59203293, 0.62292703, 0.5409094 , 0.50213883, 0.36849053],
       [0.41471592, 0.41818533, 0.44153972, 0.43655441, 0.44693686,
        0.51728155, 0.50360367, 0.56964968, 0.48017894, 0.55906542],
       [0.56327921, 0.46405485, 0.40094097, 0.44008667, 0.41026101,
        0.45690497, 0.48774946, 0.48312332, 0.4302379 , 0.49793629],
       [

## Step 8: Create Dashboard

Create a dashboard variable **called `dashboard`**.  On the top of this dashboard place the label widget (`heatmap_label`) and on the bottom place the figure (`fig`).

In [8]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
dashboard = widgets.VBox([heatmap_label, fig])
print(dashboard)

        0.51175678, 0.49517039, 0.45929713, 0.43190783, 0.59102649],
       [0.44849294, 0.4749017 , 0.61039877, 0.6646432 , 0.38957005,
        0.46973143, 0.45961324, 0.46447998, 0.43728366, 0.62463639],
       [0.54350696, 0.43311305, 0.48503318, 0.56656882, 0.55200711,
        0.59203293, 0.62292703, 0.5409094 , 0.50213883, 0.36849053],
       [0.41471592, 0.41818533, 0.44153972, 0.43655441, 0.44693686,
        0.51728155, 0.50360367, 0.56964968, 0.48017894, 0.55906542],
       [0.56327921, 0.46405485, 0.40094097, 0.44008667, 0.41026101,
        0.45690497, 0.48774946, 0.48312332, 0.4302379 , 0.49793629],
       [0.57996281, 0.5182848 , 0.58460319, 0.471571  , 0.5122255 ,
        0.51749191, 0.52746438, 0.64852668, 0.52489542, 0.55149071],
       [0.46143442, 0.52405098, 0.51620815, 0.425521  , 0.38434132,
        0.53234389, 0.50231104, 0.56949764, 0.54068199, 0.46302624],
       [0.45047681, 0.4806207 , 0.60702669, 0.61403293, 0.43086284,
        0.50274816, 0.40697328, 0.5788741